### ISSUE TITLE
Problem with the configuration of Maven POM:

### ISSUE THREAD

**Issue by emejoti** [authzforce/fiware#11]
Hi, i'm following the step to make an Attribute Provider (http://authzforce-ce-fiware.readthedocs.io/en/latest/UserAndProgrammersGuide.html#making-an-attribute-provider) and I'm having some problems with the fourth step. When I copy the build plugin configuration, it shows an error at the execution label. If I remove it then shows an error at the id label, then at the phase, etc.

This is the code:     
```
<execution>
     <id>jaxb-generate-compile-sources</id> <phase>generate-sources</phase> <goals>
      <goal>generate</goal>
     </goals>
 </execution>
```

And the error that Eclipse shows is this: Plugin execution not covered by lifecycle configuration: doc-examples:lambda-java-example:0.13.0:generate (execution: 
 jaxb-generate-compile-sources, phase: generate-sources)

Thanks.

**Comment by cdanger** [comment]
You can ignore this. If this is disturbing, Eclipse should suggest a Quick Fix to ignore this.

Just run Maven generate-sources as told in the doc:
```
$ mvn generate-sources
```
Or use Eclipse on the Maven project: Run as > Maven generate-sources
https://books.sonatype.com/m2eclipse-book/reference/running-sect-running-maven-builds.html

**Comment by emejoti** [comment]
It's supposed to generate the JAXB-annotated class(es), but only generate the folders

**Comment by cdanger** [comment]
Is there anything to generate? Do you have an XML schema? Did you include it in the schema used by maven-jaxb2-plugin (POM configuration) ?

**Comment by emejoti** [comment]
Everything fixed, thanks.
