### ISSUE TITLE
Provide versioned tags for the docker images.

### ISSUE THREAD

**Issue by dmabtrg** [authzforce/fiware#3]
The [FIWARE Docker guidelines](http://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/Docker) says:

> At least a Docker container tag associated with the latest stable release MUST be present in Dockerhub. 

The new automated image only has the `latest` tag.

Please add versioned tags to the docker image, at least for the latest stable release ([4.4.1.b](https://github.com/authzforce/fiware/releases/tag/release-4.4.1b)).

**Comment by cdanger** [comment]
Tag 4.4.1b is now available in docker tags:
https://hub.docker.com/r/fiware/authzforce-ce-server/tags/

**Comment by dmabtrg** [comment]
Thanks.
